# Generated by Django 2.2.14 on 2020-07-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200707_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='emp',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='subpage',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='test',
        ),
    ]
