# Generated by Django 2.2.14 on 2020-07-07 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0004_auto_20200707_1113"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="emp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customtext_emp",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="name",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="subpage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customtext_subpage",
                to="home.CustomText",
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customtext_test",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
